config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'static_pages#new'
  resources :static_pages, only: %i[new create]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  require 'sidekiq/web'

  Rails.application.routes.draw do
    Sidekiq::Web.use(Rack::Auth::Basic) do |user_id, password|
      [user_id, password] == [ENV['SIDEKIQ_BASIC_ID'], ENV['SIDEKIQ_BASIC_PASSWORD']]
    end
    mount Sidekiq::Web, at: '/sidekiq'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def new ; end

  def create
    email = params[:email]
    SendEmailJob.set(wait_until: Time.zone.now + 10.minutes).perform_later(email) #10分後に実行するジョブをキューに追加
    redirect_to new_static_page_path, notice: 'メールを送信のキューを追加しました'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light" lang="ja">
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= render 'shared/flash' if notice %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div id="notification" class="alert alert-success flex justify-center default_width mx-auto">
    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
    <span><%= notice %></span>
  </div>
<% end %>

app/views/static_pages/new.html.erb
<div class="flex justify-center">
  <h1 class="text-2xl font-bold">入力したメールアドレスに10分後にメール送信</h1>
</div>
<div class="flex justify-center mt-20">
  <%= form_with url: static_pages_path, local: true, method: :post do |form| %>
  <div class="mb-4">
    <%= form.label :email, "メールアドレス" %>
    <%= form.email_field :email, class: "input input-bordered border border-black w-full" %>
  </div>

  <div class="flex justify-center">
    <%= form.submit "送信する", class: "btn btn-outline" %>
  </div>
<% end %>
</div>